#load routes from database storing by IphpCoreBundle
_main:
    resource: "@IphpCoreBundle/Resources/config/routing.yml"

fos_user_all:
    resource: "@IphpCoreBundle/Resources/config/routing/fos_user.yml"


iphpsandbox_photo:
    pattern:  /photo/
    defaults: { _controller: IphpsandboxPhotoBundle:Photo:index }

iphpsandbox_photo_edit:
    pattern:  /photo/{id}/
    defaults: { _controller: IphpsandboxPhotoBundle:Photo:edit }