iphpsandbox_photo:
    resource: "@IphpsandboxPhotoBundle/Resources/config/routing.xml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_main:
    resource: "@IphpCoreBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


iphpsandbox_photo:
    pattern:  /photo/
    defaults: { _controller: IphpsandboxPhotoBundle:Photo:index }

iphpsandbox_photo_edit:
    pattern:  /photo/{id}/
    defaults: { _controller: IphpsandboxPhotoBundle:Photo:edit }